### 1.	Write a Python Program to Add Two Matrices?

#### Solution 1

In [32]:
import numpy as np
x = np.random.randint(0,20,12).reshape(4,3)
y = np.random.randint(0,20,12).reshape(4,3)

In [33]:
x

array([[ 6,  1,  7],
       [13,  7, 19],
       [ 5,  6,  2],
       [12, 13, 18]])

In [34]:
y

array([[19, 14,  7],
       [14,  8, 17],
       [ 6, 13, 19],
       [14, 11,  7]])

In [35]:
result = [[0,0,0],
          [0,0,0],
          [0,0,0],
          [0,0,0]]

In [36]:
# iterate through rows
for i in range(len(x)):
   # iterate through columns
   for j in range(len(x[0])):
       result[i][j] = x[i][j] + y[i][j]

In [37]:
for r in result:
    print(r)

[25, 15, 14]
[27, 15, 36]
[11, 19, 21]
[26, 24, 25]


#### Soultion 2 - Using list comprehension

In [39]:
X = np.random.randint(0,20,12).reshape(4,3)
Y = np.random.randint(0,20,12).reshape(4,3)

In [40]:
X

array([[10, 15, 19],
       [ 5,  2,  4],
       [ 5,  8,  1],
       [11, 17, 18]])

In [41]:
Y

array([[14, 14, 17],
       [ 0,  6, 14],
       [19,  6, 10],
       [ 0, 15,  7]])

In [47]:
result = [[X[i][j] + Y[i][j] for j in range(len(X[0]))] for i in range(len(X))]
for r in result:
    print(r)

[24, 29, 36]
[5, 8, 18]
[24, 14, 11]
[11, 32, 25]


### 2.	Write a Python Program to Multiply Two Matrices?

In [6]:
Mat1 = np.random.randint(0,20,9).reshape(3,3)
Mat2 = np.random.randint(0,20,12).reshape(3,4)

In [7]:
Mat1

array([[ 3, 12, 11],
       [ 4,  8, 18],
       [ 9, 15,  8]])

In [8]:
Mat2

array([[12, 10, 14,  6],
       [15, 19,  8, 10],
       [15,  0,  3, 14]])

In [9]:
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

# iterate through columns of Matrix 1

for i in range(len(Mat1)):

    # iterate through columns of Matrix 2
    
    for j in range(len(Mat2[0])):
        
        # iterate through rows of Matrix 2
        
        for k in range(len(Mat2)):
            result[i][j] += Mat1[i][k] * Mat2[k][j]

for r in result:
    print(r)

[381, 258, 171, 292]
[438, 192, 174, 356]
[453, 375, 270, 316]


### 3.	Write a Python Program to Transpose a Matrix?

In [13]:
matrix = np.random.randint(0,20,6).reshape(3,2)
matrix

array([[19, 13],
       [13,  1],
       [ 5, 12]])

In [21]:
result = [[0,0,0],
          [0,0,0]]

# iterate through rows of matrix

for i in range(len(matrix)):
    
    # iterate through columns of matrix
    
    for j in range(len(matrix[0])):
        result[j][i] = matrix[i][j]

for r in result:
    print(r)

[19, 13, 5]
[13, 1, 12]


### 4.	Write a Python Program to Sort Words in Alphabetic Order?

In [3]:
str = input('Please enter a sentence: ')

sentence = str.split()
sentence.sort()

for word in sentence:
    print(word)

Please enter a sentence: if you wish to make an apple pie from scratch you must first invent the universe
an
apple
first
from
if
invent
make
must
pie
scratch
the
to
universe
wish
you
you


### 5.	Write a Python Program to Remove Punctuation From a String?

In [12]:
punctuation = '.?""''`~;:,-!()[]/\{}<>*_^@#$%&'

str = input('Enter a sentence with punctuations: ')

sentence = ''

for char in str:
    if char not in punctuation:
        sentence += char

print(sentence)

Enter a sentence with punctuations: My *Name &is Pankaj ^%&.and<> I love?>_ Data @Science.
My Name is Pankaj and I love Data Science
