### 1.	Write a Python Program to find sum of array?

In [2]:
import numpy as np
array = np.arange(14)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [2]:
sum = 0
for i in range(len(array)):
    sum += array[i]
print(f'Sum of Array is {sum}')

Sum of Array is 91


### 2.	Write a Python Program to find largest element in an array?

In [3]:
array = []

for i in range(1, 10):
    n = int(input('Enter a number: '))
    array.append(n)
print(array) 

Enter a number: 26
Enter a number: 549
Enter a number: 25
Enter a number: 5
Enter a number: 964
Enter a number: 25
Enter a number: 6
Enter a number: 54
Enter a number: 85
[26, 549, 25, 5, 964, 25, 6, 54, 85]


In [4]:
array

[26, 549, 25, 5, 964, 25, 6, 54, 85]

In [5]:
print(f'Largest element in array {array} is', sorted(array)[-1])

Largest element in array [26, 549, 25, 5, 964, 25, 6, 54, 85] is 964


### 3.	Write a Python Program for array rotation?

In [6]:
def rotateArray(a,d):
    temp = []
    n=len(a)
    for i in range(d,n):
        temp.append(a[i])
    i = 0
    for i in range (0,d):
        temp.append(a[i])
    a=temp.copy()
    return a
 
arr = [1, 2, 3, 4, 5, 6, 7]
print("Array after left rotation is: ", end=' ')
print(rotateArray(arr, 2))

Array after left rotation is:  [3, 4, 5, 6, 7, 1, 2]


### 4.	Write a Python Program to Split the array and add the first part to the end? 

In [14]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
def split_array(arr, n, k):
    for i in range(0,k):
        x = arr[0]
        for j in range(0,n-1):
            arr[j] = arr[j+1]
        arr[n-1] = x

arr = array
n = len(arr)
k = int(input('Enter the number of elements to split: '))

split_array(arr, n, k)

for i in range(0,n):
    print(arr[i], end= ' ')


Enter the number of elements to split: 6
6 7 8 9 0 1 2 3 4 5 

### 5.	Write a Python Program to check if given array is Monotonic?

In [32]:
arr = np.random.randint(10,100, 20)
arr

array([43, 42, 87, 22, 11, 61, 23, 28, 55, 84, 16, 11, 86, 49, 19, 56, 83,
       54, 63, 29])

In [33]:
if all((arr[i] <= arr[i+1] for i in range(len(arr)-1)) or (arr[i] >= arr[i+1] for i in range(len(arr)-1))):
       print(f"{arr} is a Monotonic Array")
else:
    print(f"{arr} is not a Monotnic Array")

[43 42 87 22 11 61 23 28 55 84 16 11 86 49 19 56 83 54 63 29] is not a Monotnic Array


In [36]:
arr1 = [2,4,6,8,10,12,14]
if all((arr1[i] < arr1[i+1] for i in range(len(arr1)-1)) or (arr[i] > arr[i+1] for i in range(len(arr1)-1))):
    print(f"{arr1} is a Monotonic Array")
else:
    print(f"{arr1} is not a Monotnic Array")

[2, 4, 6, 8, 10, 12, 14] is a Monotonic Array
